### ISSUE TITLE
flask-connexion-rest-part-4 incompatible with newer package versions

### ISSUE THREAD

**Issue by josvos** [realpython/materials#104]
I'm trying to port flask-connexion-rest-part-4 to the latest versions of all package dependencies and after fixing a few incompatibilities (that I can share) the server is running, but when accessing just "/" it fails with this error: 

ValueError: Invalid fields for <NotePersonSchema(many=False)>: {'notes'}.

Any suggestions on what's causing this?

**Comment by dbader** [comment]
Pinging @writeson here since he's the author of that series :)

**Comment by writeson** [comment]
Hi Jos,
I guess I need some more context about what you're doing so I can try to replicate the problem you're seeing and suggest a course of action. Can you give me more information?
Thanks!
Doug

**Comment by josvos** [comment]
Hi, will replicate it in an unmodified version (in my version, I removed the Flask-SQLAlchemy dependency and use bare SQLAlchemy, but as this is working fine with the old packages, I suppose this is not causing the problem).  Stay tuned...

**Comment by josvos** [comment]
OK. attached my package list (requirements01.txt) and a patch (patch01.txt) as the "strict" keyword parameter for ModelSchema is implicit now and invalid to specify.  When you make a virtualenv with these packages, apply the pacth to the code (part-4), run "python3 build_database.py; python3 server.py", just visiting http://localhost:5000/ produces the error.  I'm using Python 3.7.5.

[requirements01.txt](https://github.com/realpython/materials/files/4308252/requirements01.txt)
[patch01.txt](https://github.com/realpython/materials/files/4308263/patch01.txt)

**Comment by acsany** [comment]
Hi @josvos ! We recently updated the [Real Python Flask REST API tutorial](https://realpython.com/flask-connexion-rest-api/) and the code should work again now 🥳
