### ISSUE TITLE
Flask-Google-login Error: Got unexpected extra argument (run)

### ISSUE THREAD

**Issue by Doombite** [realpython/materials#156]
Hello! I was working on adding this to one of my projects when I got an error, so I installed the example and got the same error:
Usage: flask [OPTIONS]
Try 'flask --help' for help.

Error: Got unexpected extra argument (run)

I found that when I removed `@click.command("init-db")` (Line 33, From db.py) that I didnt get the error anymore, Does anyone know what I can do to fix this?

My python version is 3.9.0

Sorry If this seems messy or incorrect (this is the first time I posted an issue)

**Comment by Znunu** [comment]
Try to ping the author

**Comment by dbader** [comment]
Hi there, the best way to get support for courses & articles is to join one of our [weekly Office Hours calls](https://realpython.com/office-hours/) or in the [RP Community Slack](https://realpython.com/community/). See you there :)
