### ISSUE TITLE
Django Diary "TemplateDoesNotExist"

### ISSUE THREAD

**Issue by indomitable-enigma** [realpython/materials#216]
Hello,

I just finished up to the end of step 3 in the Django Diary tutorial, but the web application is still throwing the following error:

TemplateDoesNotExist at /
entries/entry_list.html

I've double and triple checked that all my code is correct and all the files are in the proper directory, but at this point I'm at a loss. Screenshot of the error below. Any help would be massively appreciated.

![image](https://user-images.githubusercontent.com/89283470/130305165-2e5bdf49-9e9e-4973-8a04-1f54869df361.png)

**Comment by acsany** [comment]
Hi @indomitable-enigma, sorry for my ridiculously late reply. I hope you worked things out by now. If not, please leave a comment at the article, and I’ll have a look there: https://realpython.com/django-diary-project-python/ 🙂
