### ISSUE TITLE
requirements.txt includes "pkg-resources==0.0.0"

### ISSUE THREAD

**Issue by benhunter** [realpython/materials#30]
This is for the `concurrency-overview` folder. (Editing because I realized there are many other tutorials in this repository.)

`concurrency-overview/requirements.txt` includes the line "pkg-resources==0.0.0", which causes `pip install -r .\requirements.txt` to fail with: ```Could not find a version that satisfies the requirement pkg-resources==0.0.0 (from -r .\requirements.txt (line 23)) (from versions: )
No matching distribution found for pkg-resources==0.0.0 (from -r .\requirements.txt (line 23))```

This is on Windows 10 with Python 3.6.4. This question on StackOverflow looks to be the same issue: [https://stackoverflow.com/questions/39577984/what-is-pkg-resources-0-0-0-in-output-of-pip-freeze-command](https://stackoverflow.com/questions/39577984/what-is-pkg-resources-0-0-0-in-output-of-pip-freeze-command)

Removing the line "pkg-resources==0.0.0" from `requirements.txt` fixes the issue.

**Comment by gahjelle** [comment]
@jima80525 :blush:

**Comment by jima80525** [comment]
@benhunter  - 
Thanks!  I just submitted a PR to remove this line.  Thanks for taking the time to point this out!

jima

**Comment by dbader** [comment]
Closing—thx!
