### ISSUE TITLE
learning resources for tic-tac-toe bonus source code with performance tricks used

### ISSUE THREAD

**Issue by yoicomment** [realpython/materials#473]
Hello,

in the following link (https://github.com/realpython/materials/tree/master/tic-tac-toe-ai-python/source_code_bonus/tic-tac-toe) some performance tricks are applied to the minimax algorithm for the tic-tac-toe implementation.
I would like to know where I can find the associated blog posts. One obvious performance trick that was used is related to the minimax.json file. I would like to read more on this trick and alle the other tricks that were applied to the minimax algorithm in the above link. Anyone knows more? And if there aren't any associated blog posts on RP, then could you share some learning resources about the used tricks?

Any help would be highly appreciated!

**Comment by gahjelle** [comment]
Hi @yoicomment and thanks for reaching out.

We have two tutorials about minimax:

- https://realpython.com/python-minimax-nim/
- https://realpython.com/tic-tac-toe-ai-python/

These don't go in detail about the `minimax.json` file, though. However, that file is used as a precomputed table which is mentioned as a next step challenge in https://realpython.com/tic-tac-toe-ai-python/#next-steps The file `minimax.py` shows how the JSON file is computed and stored to disk.

I hope this gives you some ideas for further explorations?

**Comment by yoicomment** [comment]
So, is the minimax.json file part of "Caching" which is listed in the next step challenges?:

> Caching: You can precompute the entire game tree up front, which would be a one-time effort requiring a lot of resources. Later, you’d be able to load the [lookup table (LUT)](https://en.wikipedia.org/wiki/Lookup_table) into the memory and get the score instantly for every possible game state.

**Comment by gahjelle** [comment]
Yes, exactly. The JSON file contains the result of calculating all 30000 or so nodes in the full game tree.

**Comment by yoicomment** [comment]
Ok, thanks for the quick replies!
And btw., the tictactoe and minimax tutorial was great! I learned a lot today :D
