### ISSUE TITLE
Wrong version linked for Building Out the Complete API

### ISSUE THREAD

**Issue by cooknl** [realpython/materials#5]
https://realpython.com/flask-connexion-rest-api/

Building Out the Complete API

Includes the paragraph
To achieve this, you’ll extend both the swagger.yml and people.py files to fully support the API defined above. For the sake of brevity, only a link will be provided for both files:

[swagger.yml](https://github.com/realpython/materials/blob/master/flask-connexion-rest/version_2/swagger.yml)
[people.py](https://github.com/realpython/materials/blob/master/flask-connexion-rest/version_2/people.py)

The links are to the version_2 files, which are not "extended" with the full API, so won't give the Swagger UI output that follows.

I believe you intended to use the version_3 files?

**Comment by writeson** [comment]
Thanks for the notification, I've corrected the article content to link to the correct version of the example files (3, as you mentioned) for that part of the article.
